# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myWeb3Wallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myWeb3Wallet
#pod 'web3swift', :git => 'https://github.com/waterwang1992/TBWeb3swift.git', :branch => 'tb_3_0_6'

  pod 'TBWeb3swift', :path => '../../../TBWeb3swift', :inhibit_warnings => true
   pod 'TBWeb3SwiftCore', :path => '../../../TBWeb3swift', :inhibit_warnings => true

  target 'myWeb3WalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myWeb3WalletUITests' do
    # Pods for testing
  end

end
